# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    type: xml

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /cart

app:
    resource: '@AppBundle/Controller/'
    type: annotation

